// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Activity = Collections['activities']['schema']['_output']
export declare const activities: Activity[]

export type Formation = Collections['formations']['schema']['_output']
export declare const formations: Formation[]
